name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Start SSH agent and add the private key
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

        # Deploy files to EC2
        rsync -avz --delete ./build/ ubuntu@ec2-13-201-21-180.ap-south-1.compute.amazonaws.com:/home/ubuntu/my-react-app/

        # SSH into EC2 and restart Nginx to serve the new build
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-201-21-180.ap-south-1.compute.amazonaws.com << 'EOF'
          sudo cp -r /home/ubuntu/my-react-app/* /var/www/html/
          sudo systemctl restart nginx
        EOF
