name: Deploy Vite React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Set environment variables
        run: |
          echo "VITE_API_URL=https://marketme.site" >> .env
          echo "API_KEY=123" >> .env

      - name: Build the Vite app
        run: |
          npm run build

      - name: Deploy to Nginx
        run: |
          echo "Deploying to Nginx"
          # Save the PEM file temporarily
          echo "${{ secrets.EC2_SSH_KEY }}" > my_key.pem
          chmod 600 my_key.pem
          
          # Deploy using SSH
          scp -o StrictHostKeyChecking=no -i my_key.pem -r dist/* ubuntu@13.202.207.72:/var/www/html/
          ssh -o StrictHostKeyChecking=no -i my_key.pem ubuntu@13.202.207.72 "sudo systemctl restart nginx"

      - name: Clean up
        run: |
          rm my_key.pem
