name: Deploy Vite React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the Vite app
        run: |
          npm run build

      - name: Deploy to Nginx
        run: |
          echo "Deploying to Nginx"
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/

      - name: Restart Nginx
        run: |
          echo "Restarting Nginx"
          sudo systemctl restart nginx
